"""Embedded emoji data for the Emoji tab.

Each entry is "<emoji> <space separated search keywords>".
The first keyword(s) form the human readable name shown in the tooltip.
"""
from __future__ import annotations

EMOJI_CATEGORIES: list[tuple[str, list[str]]] = [
    (
        "Smileys & emotion",
        [
            "😀 grinning face happy",
            "😃 smiley big eyes happy",
            "😄 smile happy eyes",
            "😁 beaming grin teeth",
            "😆 laughing squint",
            "😅 sweat smile relief",
            "🤣 rofl rolling on the floor laughing",
            "😂 tears of joy laugh lol",
            "🙂 slight smile",
            "🙃 upside down face silly",
            "😉 wink",
            "😊 blush smiling eyes",
            "😇 angel halo innocent",
            "🥰 smiling face with hearts love",
            "😍 heart eyes love",
            "🤩 star struck wow",
            "😘 blowing kiss",
            "😋 yum delicious tasty",
            "😛 tongue out",
            "😜 wink tongue crazy",
            "🤪 zany goofy",
            "🤗 hugging face hug",
            "🤔 thinking hmm",
            "🤐 zipper mouth secret",
            "😐 neutral face",
            "😑 expressionless",
            "😶 no mouth silent",
            "😏 smirk",
            "😒 unamused",
            "🙄 eye roll",
            "😬 grimace awkward",
            "😌 relieved calm",
            "😔 pensive sad",
            "😴 sleeping zzz tired",
            "😷 face mask sick",
            "🤒 thermometer sick fever",
            "🤯 mind blown exploding head",
            "🥳 party celebrate birthday",
            "😎 cool sunglasses",
            "🤓 nerd glasses",
            "😕 confused",
            "😟 worried",
            "😢 crying sad tear",
            "😭 sobbing loudly crying",
            "😱 scream fear shock",
            "😡 angry mad rage",
            "🥺 pleading puppy eyes",
            "😳 flushed embarrassed",
            "🥵 hot face",
            "🥶 cold face freezing",
            "😈 smiling devil imp",
            "💀 skull dead",
            "👻 ghost",
            "🤖 robot",
            "💩 pile of poo",
        ],
    ),
    (
        "Gestures & people",
        [
            "👍 thumbs up like yes approve",
            "👎 thumbs down dislike no",
            "👌 ok hand perfect",
            "✌️ victory hand peace",
            "🤞 crossed fingers luck",
            "🤟 love you gesture",
            "🤘 rock on horns",
            "👈 point left",
            "👉 point right",
            "👆 point up",
            "👇 point down",
            "☝️ index pointing up",
            "✋ raised hand stop",
            "👋 waving hand hello bye",
            "🤙 call me hand",
            "💪 flexed biceps strong muscle",
            "🙏 folded hands pray thanks please",
            "👏 clapping hands applause",
            "🙌 raising hands celebrate hooray",
            "🤝 handshake deal agreement",
            "✍️ writing hand",
            "🤦 facepalm",
            "🤷 shrug",
            "👀 eyes look",
            "🧠 brain",
            "👶 baby",
        ],
    ),
    (
        "Animals & nature",
        [
            "🐶 dog face puppy",
            "🐱 cat face kitten",
            "🐭 mouse face",
            "🐹 hamster",
            "🐰 rabbit bunny",
            "🦊 fox",
            "🐻 bear",
            "🐼 panda",
            "🐨 koala",
            "🐯 tiger",
            "🦁 lion",
            "🐮 cow",
            "🐷 pig",
            "🐸 frog",
            "🐵 monkey",
            "🐔 chicken",
            "🐧 penguin",
            "🐦 bird",
            "🦉 owl",
            "🦋 butterfly",
            "🐝 honeybee bee",
            "🐢 turtle",
            "🐍 snake",
            "🐙 octopus",
            "🐬 dolphin",
            "🐳 whale",
            "🌸 cherry blossom flower",
            "🌹 rose flower",
            "🌻 sunflower",
            "🌲 evergreen tree",
            "🌵 cactus",
            "🍀 four leaf clover luck",
        ],
    ),
    (
        "Food & drink",
        [
            "🍎 red apple fruit",
            "🍌 banana",
            "🍇 grapes",
            "🍓 strawberry",
            "🍉 watermelon",
            "🍊 orange tangerine",
            "🍋 lemon",
            "🍍 pineapple",
            "🥑 avocado",
            "🍅 tomato",
            "🥕 carrot",
            "🌽 corn",
            "🍞 bread",
            "🧀 cheese",
            "🍳 fried egg cooking",
            "🥓 bacon",
            "🍔 hamburger burger",
            "🍟 french fries",
            "🍕 pizza",
            "🌭 hot dog",
            "🌮 taco",
            "🍣 sushi",
            "🍜 ramen noodles",
            "🍦 ice cream",
            "🍩 doughnut donut",
            "🍪 cookie",
            "🎂 birthday cake",
            "🍫 chocolate",
            "☕ coffee hot beverage",
            "🍵 tea",
            "🍺 beer",
            "🍷 wine",
            "🥂 clinking glasses cheers",
            "🥤 cup with straw soda",
        ],
    ),
    (
        "Activities & objects",
        [
            "⚽ soccer ball football",
            "🏀 basketball",
            "🏈 american football",
            "🎾 tennis",
            "🎮 video game controller",
            "🎲 game die dice",
            "🎯 direct hit target bullseye",
            "🎵 musical note music",
            "🎧 headphones",
            "🎸 guitar",
            "🎬 clapper board movie",
            "🎨 artist palette art",
            "🏆 trophy winner",
            "🥇 gold medal first place",
            "🎁 wrapped gift present",
            "🎉 party popper tada",
            "🎈 balloon",
            "💻 laptop computer",
            "📱 mobile phone",
            "⌨️ keyboard",
            "🖥️ desktop computer",
            "📷 camera",
            "💡 light bulb idea",
            "🔋 battery",
            "🔒 locked padlock",
            "🔑 key",
            "🔧 wrench tool",
            "📌 pushpin pin",
            "📎 paperclip",
            "📝 memo note write",
            "📚 books",
            "📧 email envelope",
            "📅 calendar date",
            "⏰ alarm clock",
            "💰 money bag",
            "🛒 shopping cart",
        ],
    ),
    (
        "Travel & weather",
        [
            "🚗 automobile car",
            "🚕 taxi",
            "🚌 bus",
            "🚲 bicycle bike",
            "🏍️ motorcycle",
            "✈️ airplane plane flight",
            "🚀 rocket launch",
            "🚁 helicopter",
            "⛵ sailboat",
            "🚂 locomotive train",
            "🏠 house home",
            "🏢 office building",
            "🏥 hospital",
            "🏖️ beach umbrella",
            "⛰️ mountain",
            "🌍 globe earth europe africa",
            "🌙 crescent moon night",
            "⭐ star",
            "☀️ sun sunny",
            "☁️ cloud",
            "🌧️ rain cloud",
            "⛄ snowman snow",
            "🔥 fire hot flame",
            "🌈 rainbow",
            "⚡ high voltage lightning zap",
        ],
    ),
    (
        "Symbols",
        [
            "❤️ red heart love",
            "🧡 orange heart",
            "💛 yellow heart",
            "💚 green heart",
            "💙 blue heart",
            "💜 purple heart",
            "🖤 black heart",
            "💔 broken heart",
            "✨ sparkles",
            "💯 hundred points perfect",
            "✅ check mark button done",
            "❌ cross mark no",
            "⚠️ warning",
            "❓ question mark",
            "❗ exclamation mark",
            "➕ plus",
            "➖ minus",
            "➡️ right arrow",
            "⬅️ left arrow",
            "⬆️ up arrow",
            "⬇️ down arrow",
            "🔄 counterclockwise arrows refresh",
            "✔️ check mark",
            "©️ copyright",
            "™️ trade mark",
            "♻️ recycling symbol",
            "🔴 red circle",
            "🔵 blue circle",
        ],
    ),
]


def parse_entry(entry: str) -> tuple[str, str]:
    """Split "<emoji> <keywords>" into (emoji, lowercase keywords)."""
    emoji, _, words = entry.partition(" ")
    return emoji, words.casefold()
